sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g coveralls
script:
   - make ci
notifications:
  irc: "irc.freenode.org#bucharest-gold"
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info | coveralls
